#cloud-config

package_update: true
package_upgrade: true

packages:
  - curl
  - wget
  - tar
  - gzip
  - nginx


runcmd:
  - systemctl start nginx
  - mkdir -p /var/www/webapp1
  - echo "<h1>My NGINX Site - Web App 1</h1>" | sudo tee /var/www/webapp1/index.html
  - systemctl enable nginx