name: Provision Azure Resources with Terraform
on: workflow_dispatch
permissions:
  id-token: write
  contents: read
  
jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: 1.15.4

      - name: Terraform Init
        run: cd infra && terraform init
      
      - name: azure login
        uses: azure/login@v3
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Terraform Apply
        id: apply
        run: cd infra && terraform apply --auto-approve --target=cloudflare_dns_record.gowtham_living
        env:
            TF_VAR_admin_password: ${{ secrets.ADMIN_PASSWORD }}
            TF_VAR_admin_username: ${{ vars.ADMIN_USERNAME }}
            TF_VAR_cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
            TF_VAR_zone_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
      - name: Output results
        run: echo ${{ steps.apply.outputs.ip }}


